name: Version
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore: version packages')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
      - name: Set Node Version
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Create Release Pull Request
        uses: changesets/action@master
        with:
          title: "chore: version packages"
          commit: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
